### ISSUE TITLE
Suppress MonoMod Added?

### ISSUE THREAD

**Issue by iamwyza** [0x0ade/MonoMod#18]
Is there a way to surpress the [MonoModAdded] attribute? (possibly for a class or even better a namespace?)

I have several classes that I'm adding to the assembly, but those are basically just a straight "copy" into the target assembly (under a namespace of "Modding").  I really I only need the added attribute for methods/classes that are done inside of one of the namespaces in the target assembly.  

It's not a huge deal, it just clutters up the classes/methods with necessary fluff for stuff that I'm adding that is entirely new.

**Comment by 0x0ade** [comment]
You can set the environment variable `MONOMOD_CLEANUP_ALL` to `1` before running MonoMod. Put the following line above the one starting MonoMod:
* .bat: `SET MONOMOD_CLEANUP_ALL=1`
* .sh: `export MONOMOD_CLEANUP_ALL=1`

This removes all MonoMod references and attributes from the target assembly. It will cause issues when using RuntimeDetour or anything similar from MonoMod at runtime, though.

**Comment by iamwyza** [comment]
Hmm.  I'd prefer it to be more granular.  I like that it shows where It shows that it's modified the existing namespaces/classes/methods/properties of the target assembly.  It'd just be nice if we could suppress it for a given area. (even if it was just at the class level, that'd work too)

**Comment by 0x0ade** [comment]
I don't want to check for a dozen environment variables / program arguments, though :/

Now that I'm thinking about it, maybe...

```cs
public Func<ICustomAttributeProvider, TypeReference, bool> ShouldCleanupAttrib;
```

... inside of MonoModder, settable via ...

```cs
using System;
using MonoMod;
using MonoMod.InlineRT;
using Mono.Cecil;

namespace MonoMod {
    static class MonoModRules {

        static MonoModRules() {
            MMILRT.Modder.ShouldCleanupAttrib = IsUselessAttrib;
        }

        public static bool IsUselessAttrib(ICustomAttributeProvider holder, TypeReference attribType) {
            // If the attribute isn't a MonoMod attribute, it's "useful."
            if (!attribType.Namespace.StartsWith("MonoMod") && !attribType.Name.StartsWith("MonoMod"))
                return false;
            TypeDefinition type = holder as TypeDefinition ??
                (holder as MethodDefinition)?.DeclaringType ??
                (holder as FieldDefinition)?.DeclaringType ??
                (holder as PropertyDefinition)?.DeclaringType;
            // If the holding type (or the holding method's type) is inside the Modding namespace, return true.
            return type == null || type.FullName.StartsWith("Modding.");
        }
    }
}
```

... would do the job?

**Comment by 0x0ade** [comment]
Don't get me wrong, I very much like the idea of granular configuration, but I prefer going "all in or nothing" - either give the user an "on / off switch," or give the user the option to program their own conditions.

**Comment by iamwyza** [comment]
That works for me.  making it configurable through code works and means that existing functionality should continue to work while providing the flexibility for the implementer to do what they want.

**Comment by iamwyza** [comment]
Tested and working.  Interestingly, this suppresses oddities in #19 for Namespaces that remove the useless attributes.
