### ISSUE TITLE
EventDefinition / EventReference not taken into account

### ISSUE THREAD

**Issue by iamwyza** [0x0ade/MonoMod#19]
For some reason MonoMod is changing how events are being migrated slightly.  I don't know that it actually changes their functionality.  But it seems to take something that is fairly simple and makes it exceptionally verbose.

```csharp
        [HookInfo("Called at the end of the attack function", "HeroController.Attack")]
        public event AfterAttackHandler AfterAttackHook;

        public void AfterAttack(AttackDirection dir)
        {
            AfterAttackHook?.Invoke(dir);
        }

```
is instead moved into the new assembly as:
```csharp
[MonoModAdded]
public void AfterAttack(AttackDirection dir)
{
	AfterAttackHandler afterAttackHook = this.AfterAttackHook;
	if (afterAttackHook == null)
	{
		return;
	}
	afterAttackHook(dir);
}
[MonoModAdded]
[CompilerGenerated]
public void add_AfterAttackHook(AfterAttackHandler value)
{
	AfterAttackHandler afterAttackHandler = this.AfterAttackHook;
	AfterAttackHandler afterAttackHandler2;
	do
	{
		afterAttackHandler2 = afterAttackHandler;
		AfterAttackHandler value2 = (AfterAttackHandler)Delegate.Combine(afterAttackHandler2, value);
		afterAttackHandler = Interlocked.CompareExchange<AfterAttackHandler>(ref this.AfterAttackHook, value2, afterAttackHandler2);
	}
	while (afterAttackHandler != afterAttackHandler2);
}
[MonoModAdded]
[CompilerGenerated]
public void remove_AfterAttackHook(AfterAttackHandler value)
{
	AfterAttackHandler afterAttackHandler = this.AfterAttackHook;
	AfterAttackHandler afterAttackHandler2;
	do
	{
		afterAttackHandler2 = afterAttackHandler;
		AfterAttackHandler value2 = (AfterAttackHandler)Delegate.Remove(afterAttackHandler2, value);
		afterAttackHandler = Interlocked.CompareExchange<AfterAttackHandler>(ref this.AfterAttackHook, value2, afterAttackHandler2);
	}
	while (afterAttackHandler != afterAttackHandler2);
}
```

**Comment by 0x0ade** [comment]
That's #14 - I prefer your issue description, so I'll just close that one and rename this one. Thanks for giving an example 👍 

It shouldn't change it functionally. Everything that happens is that MonoMod doesn't take EventDefinitions into account. EventDefinitions consist of an `add_` and `remove_` method, similar to how properties consist of a `get_` and `set_` method.

**Comment by iamwyza** [comment]
More info here, You also get odd behavior if you modify the Add/Remove methods:
`csharp
        private event NewPlayerDataHandler _newPlayerDataHook;

        [HookInfo("Called after setting up a new PlayerData", "PlayerData.SetupNewPlayerData")]
        public event NewPlayerDataHandler NewPlayerDataHook
        {
            add
            {
                Logger.LogDebug($"[{value.Method.DeclaringType?.Name}] - Adding NewPlayerDataHook");
                _newPlayerDataHook += value;
                
            }
            remove
            {
                Logger.LogDebug($"[{value.Method.DeclaringType?.Name}] - Removing NewPlayerDataHook");
                _newPlayerDataHook -= value;
            }
        }

        public void AfterNewPlayerData()
        {
            _newPlayerDataHook?.Invoke(global::PlayerData.instance);
        }
`
becomes
`csharp
		// Token: 0x06003340 RID: 13120 RVA: 0x0012F098 File Offset: 0x0012D298
		[CompilerGenerated]
		private void remove__newPlayerDataHook(NewPlayerDataHandler value)
		{
			NewPlayerDataHandler newPlayerDataHandler = this._newPlayerDataHook;
			NewPlayerDataHandler newPlayerDataHandler2;
			do
			{
				newPlayerDataHandler2 = newPlayerDataHandler;
				NewPlayerDataHandler value2 = (NewPlayerDataHandler)Delegate.Remove(newPlayerDataHandler2, value);
				newPlayerDataHandler = Interlocked.CompareExchange<NewPlayerDataHandler>(ref this._newPlayerDataHook, value2, newPlayerDataHandler2);
			}
			while (newPlayerDataHandler != newPlayerDataHandler2);
		}

		// Token: 0x06003341 RID: 13121 RVA: 0x0012F0CD File Offset: 0x0012D2CD
		public void add_NewPlayerDataHook(NewPlayerDataHandler value)
		{
			Logger logger = ModHooks.Logger;
			string format = "[{0}] - Adding NewPlayerDataHook";
			Type declaringType = value.Method.DeclaringType;
			logger.LogDebug(string.Format(format, (declaringType != null) ? declaringType.Name : null));
			this.add__newPlayerDataHook(value);
		}

		// Token: 0x06003342 RID: 13122 RVA: 0x0012F101 File Offset: 0x0012D301
		public void remove_NewPlayerDataHook(NewPlayerDataHandler value)
		{
			Logger logger = ModHooks.Logger;
			string format = "[{0}] - Removing NewPlayerDataHook";
			Type declaringType = value.Method.DeclaringType;
			logger.LogDebug(string.Format(format, (declaringType != null) ? declaringType.Name : null));
			this.remove__newPlayerDataHook(value);
		}

		// Token: 0x06003343 RID: 13123 RVA: 0x0012F135 File Offset: 0x0012D335
		public void AfterNewPlayerData()
		{
			NewPlayerDataHandler newPlayerDataHook = this._newPlayerDataHook;
			if (newPlayerDataHook == null)
			{
				return;
			}
			newPlayerDataHook(PlayerData.instance);
		}
`

**Comment by iamwyza** [comment]
Sorry, more information on this, It appears that it actually does break the normal functionality.  Because it changes 
```csharp
        public event AfterAttackHandler AfterAttackHook;
```
to
```csharp
        private event AfterAttackHandler AfterAttackHook;
```

which of course breaks anything trying to add or remove from the hook.  So really, this turns out to be a more serious problem than we first thought.

**Comment by 0x0ade** [comment]
Does the issue still persist after your changes? If not, I guess we can close this issue

**Comment by iamwyza** [comment]
I think it's working as intended now.

**Comment by 0x0ade** [comment]
Thank you again for the pull request :)
