### ISSUE TITLE
Duplicate assembly references of differing versions

### ISSUE THREAD

**Issue by iamwyza** [0x0ade/MonoMod#21]
My target assembly has a reference to mscorlib 2.0.5.0 which I believe is some subset of the Unity version of mscorlib.  I found a way to make my merging DLL to use that, but since MonoMod injects some types into the assembly, that assembly then gets a reference to the mscorlib used by MonoMod, which is mscorlib 2.0.0.0.  This causes weird behavior in unity.  So I then have to open up the assembly in dnspy and save it in order to get it to remove that extra reference.

The types copied from a source assembly should have the reference to mscorlib changed to whatever the target assembly's version is.

**Comment by iamwyza** [comment]
Also, It should remove the reference to MonoMod.exe too. (since that reference is required to build)

**Comment by 0x0ade** [comment]
The mscorlib issue can be solved by setting up the relink map in the PatchRefs pass.  
Blindly removing the reference will break all other references due to how the tokens are referenced.  
I never saw that as critical as it never caused issues on my end when working on XnaToFna, neither using the .NET Framework, nor using mono. It could be that Unity's outdated mono fork handles things differently, though.

I'll do it this weekend :)

Regarding the MonoMod reference: It shouldn't cause issues. Some mods use f.e. the runtime relinker and thus break when removing the MonoMod reference. You can `Environment.SetEnvironmentVariable("MONOMOD_CLEANUP_ALL", "1");` in MonoModRules to get rid of the reference, though. It's the only thing affected by that environment variable at the moment.

**Comment by iamwyza** [comment]
The MonoMod reference won't be removed because MonoModWasHere holds a reference to it.

Yeah, everything compiles fine, and 99% of the game works, but sometimes it runs into places where it says it can't load the type.

**Comment by 0x0ade** [comment]
MonoMod.WasHere itself shouldn't hold any reference to MonoMod - it's an empty type added to the assembly, accessible via reflection to check if it's been modded via MonoMod.

Maybe something went completely wrong with it while patching Hollow Knight, though :/ Could you please pastebin an IL dump of that type?

Regarding the type load failures: Could you please try catching the `TypeLoadException` and log it using this method? `TypeName` doesn't get displayed under some circumstances.

```

    public static void LogDetailed(this Exception e, string tag = null) {
        for (Exception e_ = e; e_ != null; e_ = e_.InnerException) {
            Console.WriteLine(e_.GetType().FullName + ": " + e_.Message + "\n" + e_.StackTrace);
            if (e_ is ReflectionTypeLoadException) {
                ReflectionTypeLoadException rtle = (ReflectionTypeLoadException) e_;
                for (int i = 0; i < rtle.Types.Length; i++) {
                    Console.WriteLine("ReflectionTypeLoadException.Types[" + i + "]: " + rtle.Types[i]);
                }
                for (int i = 0; i < rtle.LoaderExceptions.Length; i++) {
                    LogDetailed(rtle.LoaderExceptions[i], tag + (tag == null ? "" : ", ") + "rtle:" + i);
                }
            }
            if (e_ is TypeLoadException) {
                Console.WriteLine("TypeLoadException.TypeName: " + ((TypeLoadException) e_).TypeName);
            }
            if (e_ is BadImageFormatException) {
                Console.WriteLine("BadImageFormatException.FileName: " + ((BadImageFormatException) e_).FileName);
            }
        }
    }
```

**Comment by iamwyza** [comment]
The error happens in the game, not in monomod.  My guess is that it's some basic type that for some reason it's looking at 2.0.0.0 mscorlib for, except that doesn't exist in the version of unity that the game uses.  (which explains why opening the assembly with dnspy, deleting out monomod and saving and the reference to mscorlib 2.0.0.0 goes away).

Here's part of the issue:
```
.assembly extern mscorlib as mscorlib_9
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 2:0:0:0
}
.assembly extern MonoMod
{
  .ver 17:4:6530:30093
}```

and the rest

https://gist.github.com/iamwyza/127fb41ffd707dced28d8d26507c3911

**Comment by 0x0ade** [comment]
I've created a new branch that _should_ fix the issue. I can't test it right now, though, so I depend on your test results.

https://github.com/0x0ade/MonoMod/tree/fix-multicorlib

If it works, please tell me so I can merge it into the master branch :)

**Comment by iamwyza** [comment]
I'll test it out this evening and let you know how it goes.
