### ISSUE TITLE
Publicize HookManager._HookMap (and possibly add equivalent for Detour/NativeDetour)

### ISSUE THREAD

**Issue by leo60228** [0x0ade/MonoMod#28]
It might be nice for DynamicMethodDefinition transpilers to be able to know whether a MethodBase is a detour for another MethodBase.

**Comment by 0x0ade** [comment]
`HookManager` is only used by HookGen, which is currently experiencing a revamp locally anyway. `_HookMap` is never a guarantee for all hooks.

You should rather "rely" on `Detour._DetourMap`, but even then, that doesn't account for `NativeDetour`s for obvious reasons (those will never be "mapped" in any way).

I also don't see why that would be necessary in the first place. You should know what method you're applying `DynamicMethodDefinition` on, and if it's the original method or a hook / detour in itself. To clarify: It grabs the Cecil `MethodDefinition` of the `MethodBase` you pass.

The way I want to combine it with HookGen would allow you to IL-modify the last "link" of the detour "chain" (aka the copy of the "original" method). IL manipulation in itself is already a dangerous operation, and given the nature of hooks / detours, this is the safest option for now.
