### ISSUE TITLE
How to branch inside method?

### ISSUE THREAD

**Issue by chatrat12** [0x0ade/MonoMod#36]
Trying to inject a branch into some drawing code. 

```cs
if (cursor.TryGotoNext(i => i.MatchLdcI4(1),
                       i => i.MatchLdcI4(1),
                       i => i.MatchCallvirt<OverlayManager>("Draw")))
{
    cursor.Index++;
    var jumpTo = cursor.Body.Instructions[cursor.Index + 12];
    cursor.Emit(OpCodes.Ldc_I4_0);
    cursor.Emit(OpCodes.Brfalse_S, jumpTo);
}
```

This isn't the actual branch I'm trying to do. Just thought I'd try a super simple short one in the the area I'm trying to modify. I tried a few different branch opcodes and areas to branch to. Keep getting this.
![image](https://user-images.githubusercontent.com/251682/51809769-6ef96e00-2271-11e9-84b6-c70ad6284cfe.png)
`JIT Compiler encountered an internal limitation.`

**Comment by 0x0ade** [comment]
It's hard to see what's going wrong without an IL dump of the method you're trying to patch and your actual branch.

If you want to keep them private, feel free to DM me on Discord or send me an email (check the git log for my address).

**Comment by chatrat12** [comment]
Sorry, I realize I didn't show what method I was hooking. It was the do_Draw which is a 6700 line IL dump xD 

I figured this out, I somehow overlooked a very silly mistake, don't even need a dump to find it. My `TryGotoNext` is looking for 3 instructions. then I only increment the cursor index by one... not three.

I was so convinced that something was wrong because I couldn't even get a `ret` to work. Nah, good ol' user error. Thanks for your response :D

**Comment by 0x0ade** [comment]
Great to hear that you figured it out on your own :D
