### ISSUE TITLE
DetourNativeARMPlatform is broken for dotnet32 on aarch64

### ISSUE THREAD

**Issue by leo60228** [0x0ade/MonoMod#38]
I don't have an armv7 device to test, but if it's just aarch64, there's probably something missing in https://github.com/0x0ade/MonoMod/blob/master/MonoMod.RuntimeDetour/DetourNativePlatforms.cs#L132-L211. It currently throws at https://github.com/0x0ade/MonoMod/blob/8ce8b97ab468ccd53e65b60d6da8137c44a6fbbf/MonoMod.RuntimeDetour/DetourRuntimePlatforms.cs#L65 with no further errors.

**Comment by leo60228** [comment]
Raspberry Pi 3s are aarch64, but Raspbian isn't. Install Arch Linux ARM.

**Comment by leo60228** [comment]
I just copied it from x86_64. It doesn't have native dependencies, does it?

**Comment by leo60228** [comment]
This is a huge hack, but you could try building for netstandard with the .NET SDK and executing with Mono.

**Comment by 0x0ade** [comment]
I've managed to get the RuntimeDetour tests to run on my phone another way and got different fatally crashing results.

It seems like the current ARM detours don't work properly at all. The "help wanted" label will stay as I unfortunately am completely inexperienced when it comes to ARM assembly.

**Comment by leo60228** [comment]
Ah. x30 is the link register (aka return address). x9-x15 are scratch registers, at least one of those should work.

**Comment by leo60228** [comment]
Apparently, x16 and x17 are "the Intra-Procedure-call scratch register[s]," but I'm not sure what that means. We could try those too.

**Comment by leo60228** [comment]
x18 is designated for either use by the operating system or a scratch register, but it's unclear which it is on Linux. We should avoid it, anyway.

**Comment by leo60228** [comment]
Not at home so I can't test, but try this if you can. https://gist.github.com/leo60228/b4ac9434615dcf8874ad4723d47c030d/45363a3ce0c3bc5dc236a1206d9be724cef54c3c

**Comment by leo60228** [comment]
The original issue is fixed on master, but there's some weirdness with ARM32 and a (possibly unrelated) regression preventing a release.

**Comment by leo60228** [comment]
MonoMod is now fully functional on aarch64. dotnet32 on aarch64 is still broken. armv7 is untested.

**Comment by leo60228** [comment]
Fixed in 6d1f5ed2b159cfe8cb40267be1d6f88e3a093457.

**Comment by leo60228** [comment]
Fix in the release https://github.com/0x0ade/MonoMod/releases/tag/v19.02.07.08, and EverestAPI/Everest build 800.
