### ISSUE TITLE
Overwrite private methods and insert code between lines

### ISSUE THREAD

**Issue by Ceiridge** [0x0ade/MonoMod#42]
Hi!
So far I've been able to detour methods without using _RuntimeDetours_ that I would like not to use.
Is it possible to inject code between the lines of a method and how can you overwrite a private method of a class being patched?

Or is all/most of this only possible with RuntimeDetours?
If so, can you somehow inject code (not IL instructions) at a specific point (for instance a defined IL location)/line?

**Comment by 0x0ade** [comment]
Hi! 

You can patch private methods by redefining them in your `patch_` class, just as if they were public methods. If you need to call other private methods, or if you want to manipulate methods without changing their body, make them `extern` and attach the `[MonoModIgnore]` attribute.

You can attach custom attributes to methods and let custom "rules" handle them. Those rules are defined in a `MonoModRules` class. Take a look at [this comment](https://github.com/0x0ade/MonoMod/issues/15#issuecomment-344570625) for a basic explanation and the following real world example:
- [Custom rule attribute on a method to "insert" a custom C# method between instructions.](https://github.com/EverestAPI/Everest/blob/76ff49584a5d6828c4058a14729386fd60d1d4cf/Celeste.Mod.mm/Patches/FinalBoss.cs#L36)
- [Responsible rule in MonoModRules.](https://github.com/EverestAPI/Everest/blob/76ff49584a5d6828c4058a14729386fd60d1d4cf/Celeste.Mod.mm/MonoModRules.cs#L814)

That does almost exactly what the runtime `EmitDelegate` helper does, but manually: Define your custom C# code in a separate method and inject a method call to it.

I'm going to close this issue as it's more a question than an actual issue with MonoMod itself. Feel free to continue here or [on Discord](https://discord.gg/jm7GCZB) :)
