### ISSUE TITLE
Crash when using NativeDetour and detouring to a method inside an inheriting class

### ISSUE THREAD

**Issue by bbepis** [0x0ade/MonoMod#53]
### Description
I've had a friend report that they're unable to use NativeDetour when the class that contains the method to detour to is inside a class that inherits another class.
The target method is Resources.UnloadUnusedAssets(), which is an unmanaged internal call
The game is running on Unity version 5.6.2.

MonoMod.RuntimeDetour version `18.10.22.8` is reported to work in this situation however, the ones after (not actually sure if 18.10.22.8 was the last working version, it's just a random one that does) crash with this exception:

Stack trace:
```
[Error] NullReferenceException: Object reference not set to an instance of an object
[Error] Stack trace:
MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor ()
MonoMod.RuntimeDetour.Platforms.DetourRuntimeMonoPlatform..ctor ()
MonoMod.RuntimeDetour.DetourHelper.get_Runtime ()
MonoMod.RuntimeDetour.NativeDetour..ctor (System.Reflection.MethodBase from, System.Reflection.MethodBase to)
KK_Fix_ResourceUnloadOptimizations.ResourceUnloadOptimizations.Awake ()
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
BepInEx.Bootstrap.Linker:StartBepInEx()
BepInEx.Bootstrap.Entrypoint:Init()
UnityEngine.Application:.cctor()
```

Point of failure seems to be https://github.com/0x0ade/MonoMod/blob/master/MonoMod.RuntimeDetour/Platforms/Runtime/DetourRuntimeILPlatform.cs#L47

Removing this check results in:
```
{System.NullReferenceException: Object reference not set to an instance of an object
  at MonoMod.Utils.DynamicMethodDefinition.Generate (System.Object context) [0x00000] in <filename unknown>:0 
  at MonoMod.Utils.DynamicMethodDefinition.Generate () [0x00000] in <filename unknown>:0 
  at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.CreateCopy (System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0 
  at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.TryCreateCopy (System.Reflection.MethodBase method, System.Reflection.MethodInfo& dm) [0x00000] in <filename unknown>:0 }
```

### Example
Using a patch example of this:
```cs
			var detour = new NativeDetour(typeof(Resources).GetMethod(nameof(Resources.UnloadUnusedAssets)),
				targetMethod);

			detour.Apply();
			originalUnload = detour.GenerateTrampoline<Func<AsyncOperation>>();
```

This works:
```cs
    public static class Hooks
    {
	    public static Func<AsyncOperation> originalUnload;

	    public static AsyncOperation StackTraceUnload()
	    {
			Trace.WriteLine("UNLOAD CALL");
			Trace.WriteLine(Environment.StackTrace);

		    return originalUnload();
	    }
    }
```

This, however, does not:

```cs
    public class MyPlugin : BaseUnityPlugin
    {
	    public static Func<AsyncOperation> originalUnload;

	    public static AsyncOperation StackTraceUnload()
	    {
			Trace.WriteLine("UNLOAD CALL");
			Trace.WriteLine(Environment.StackTrace);

		    return originalUnload();
	    }
    }
```

**Comment by 0x0ade** [comment]
Luckily I've already had Unity 5.6.1f1 installed on my PC and was able to create a quick test case... just to find out that detouring the method to both targets kills the editor on my end.

Gonna try to fix it this week, but no promises, given that my backlog is already piling up and I still haven't fully recovered from my bike accident last week.

**Comment by 0x0ade** [comment]
Today's "old Unity mono" discovery: **The `this` and return buffer pointers can end up at different positions than expected.**

In DetourRuntimeILPlatform, this kills the editor immediately:
```cs
private static unsafe void _SelftestGetStructHook(DetourRuntimeILPlatform self, IntPtr a, IntPtr b, IntPtr c) {
```

Meanwhile, this works just fine:
```cs
private static unsafe void _SelftestGetStructHook(IntPtr a, DetourRuntimeILPlatform self, IntPtr b, IntPtr c) {
```

Found this out via trial and error. Once the only thing that was left as a possible crash cause was the access to `self.GlueThiscallStructRetPtr`, I tried swapping the supposed `this` and return buffer positions.

Please bury me with a fork of mono from *checks 2.6 release notes* 2009.

**Comment by 0x0ade** [comment]
https://github.com/0x0ade/MonoMod/commit/a3872f663ba152a10810473435cd462eb4127c60 fixes this locally - please test and report back.

**Comment by 0x0ade** [comment]
Confirmed fixed on Discord.
